var exports,module,require,ts;"object"===typeof window&&(ts=twoside("peasy/parser.js"),require=ts.require,exports=ts.exports,module=ts.module);
(function(n,f,p){var h=[].indexOf||function(d){for(var a=0,b=this.length;a<b;a++)if(a in this&&this[a]===d)return a;return-1},m=[].slice;p.exports=function(){return function(){var d,a;a=this;d=this.base={};this.ruleIndex=0;d.parse=this.parse=function(b,e,c){null==e&&(e=a.root);null==c&&(c=0);a.data=b;a.cur=c;a.ruleStack={};a.cache={};return e()};d.rec=this.rec=function(b){var e;e=a.ruleIndex++;return function(){var c,l,d,f;l=a.ruleStack;c=null!=(f=a.cache)[e]?f[e]:f[e]={};f=a.cur;l=null!=l[f]?l[f]:
l[f]=[];if(0>h.call(l,e)){l.push(e);for(c=null!=c[f]?c[f]:c[f]=[void 0,f];;){a.cur=f;d=b();if(!d){d=c[0];a.cur=c[1];break}if(c[1]===a.cur){c[0]=d;break}c[0]=d;c[1]=a.cur}l.pop();return d}c=c[f];a.cur=c[1];return c[0]}};d.memo=this.memo=function(b){var e;e=a.ruleIndex++;return function(c){return function(){var c,d;c=null!=(d=a.cache)[e]?d[e]:d[e]={};d=a.cur;if(c=c[d])return a.cur=c[1],c[0];c=b();a.cache[e][d]=[c,a.cur];return c}}(this)};d.orp=this.orp=function(){var b,e;e=1<=arguments.length?m.call(arguments,
0):[];e=function(){var c,l,d;d=[];c=0;for(l=e.length;c<l;c++)b=e[c],"string"===typeof b?d.push(a.literal(b)):d.push(b);return d}();return function(c){return function(){var c,d,f,h;d=a.cur;f=0;for(h=e.length;f<h;f++)if(b=e[f],a.cur=d,c=b())return c}}(this)};d.andp=this.andp=function(){var b,e;e=1<=arguments.length?m.call(arguments,0):[];e=function(){var c,d,f;f=[];c=0;for(d=e.length;c<d;c++)b=e[c],"string"===typeof b?f.push(a.literal(b)):f.push(b);return f}();return function(){var c,a,d;a=0;for(d=
e.length;a<d;a++)if(b=e[a],!(c=b()))return;return c}};d.notp=this.notp=function(b){"string"===typeof b&&(b=a.literal(b));return function(){return!b()}};d.may=this.may=function(b){"string"===typeof b&&(b=a.literal(b));return function(e){return function(){var c,e;c=a.cur;if(e=b())return e;a.cur=c;return!0}}(this)};d.any=this.any=function(b){"string"===typeof b&&(b=a.literal(b));return function(a){return function(){var c,a;for(c=[];a=b();)c.push(a);return c}}(this)};d.some=this.some=function(b){"string"===
typeof b&&(b=a.literal(b));return function(){var a,c;if(c=b()){for(a=[c];c=b();)a.push(c);return a}}};d.times=this.times=function(b,e){"string"===typeof b&&(b=a.literal(b));return function(){var a,d;for(a=0;a++<e;)if(d=b())result.push(d);else return;return result}};d.list=this.list=function(b,e){null==e&&(e=a.spaces);"string"===typeof b&&(b=a.literal(b));"string"===typeof e&&(e=a.literal(e));return function(){var a,d;if(d=b()){for(a=[d];e()&&(d=b());)a.push(d);return a}}};d.listn=this.listn=function(b,
e,c){null==c&&(c=a.spaces);"string"===typeof b&&(b=a.literal(b));"string"===typeof c&&(c=a.literal(c));return function(){var a,d,f;if(f=b()){d=[f];for(a=1;a++<e;)if(c()&&(f=b()))d.push(f);else return;return d}}};d.follow=this.follow=function(b){"string"===typeof b&&(b=a.literal(b));return function(e){return function(){var c,e;c=a.cur;e=b();a.cur=c;return e}}(this)};d.literal=this.literal=function(b){return function(){var e,c;e=b.length;c=a.cur;if(a.data.slice(c,e=c+e)===b)return a.cur=e,!0}};d["char"]=
this["char"]=function(b){return function(){if(a.data[a.cur]===b)return a.cur++,b}};d.wrap=this.wrap=function(b,e,c){null==e&&(e=a.spaces);null==c&&(c=a.spaces);"string"===typeof b&&(b=a.literal(b));return function(){var a;if(e()&&(a=b()&&c()))return a}};d.spaces=this.spaces=function(){var b,e,c,d;c=a.data;d=0;for(e=a.cur;(b=c[e++])&&(" "===b||"\t"===b);)d++;a.cur+=d;return d+1};d.spaces1=this.spaces1=function(){var b,e,c;c=a.data;for(e=a.cur;(b=c[e++])&&(" "===b||"\t"===b);)lent++;a.cur+=0;return 0};
d.eoi=this.eoi=function(){return a.cur===a.data.length};d.identifierLetter=this.identifierLetter=function(){var b;b=a.data[a.cur];if("$"===b||"_"===b||"a"<=b&&"z">b||"A"<=b&&"Z">=b||"0"<=b&&"9">=b)return a.cur++,!0};d.followIdentifierLetter=this.followIdentifierLetter=function(){var b;b=a.data[a.cur];return("$"===b||"_"===b||"a"<=b&&"z">b||"A"<=b&&"Z">=b||"0"<=b&&"9">=b)&&b};d.digit=this.digit=function(){var b;b=a.data[a.cur];if("0"<=b&&"9">=b)return a.cur++,b};d.letter=this.letter=function(){var b;
b=a.data[a.cur];if("a"<=b&&"z">=b||"A"<=b&&"Z">=b)return a.cur++,b};d.lower=this.lower=function(){var b;b=a.data[a.cur];if("a"<=b&&"z">=b)return a.cur++,b};d.upper=this.upper=function(){var b;b=a.data[a.cur];if("A"<=b&&"Z">=b)return a.cur++,b};d.identifier=this.identifier=function(){var b,e,c,d;c=a.data;d=e=a.cur;b=c[e];if("a"<=b&&"z">=b||"A"<=b&&"Z">=b||"$"===b||"_"===b){for(e++;;)if(b=c[e],"a"<=b&&"z">=b||"A"<=b&&"Z">=b||"0"<=b&&"9">=b||"$"===b||"_"===b)e++;else break;a.cur=e;return c.slice(d,e)}};
d.number=this.number=function(){var b,e,c;c=a.data;e=a.cur;b=c[e];if("0"<=b&&"9">=b){for(e++;;)if(b=c[e],"0"<=b&&"9">=b)e++;else break;a.cur=e;return c.slice(start,e)}};d.string=this.string=function(){var b,e,c,d,f;f=a.data;d=e=a.cur;b=f[e];if('"'===b||"'"===b)for(c=b,e++;;)if(b=f[e],"\\"===b)e+=2;else{if(b===c)return a.cur=e+1,f.slice(d,+e+1||9E9);if(!b)break}};d.select=this.select=function(b,a){var c;console.log("select");if((c=a[b])||(c=a["default"]||a[""]))return c()}}}()})(require,exports,module);
"object"===typeof window&&(ts=twoside("peasy/lineparser.js"),require=ts.require,exports=ts.exports,module=ts.module);
(function(n,f,p){var h={}.hasOwnProperty,m=function(d,a){function b(){this.constructor=d}for(var e in a)h.call(a,e)&&(d[e]=a[e]);b.prototype=a.prototype;d.prototype=new b;d.__super__=a.prototype;return d};n=n("./parser");p.exports=function(d){function a(){var b;a.__super__.constructor.apply(this,arguments);b=this;this.parse=function(a,c,d,f,h){null==c&&(c=b.root);null==d&&(d=0);b.data=a;b.cur=d;b.trail=new Trail;b.ruleStack={};b.cache={};return c()}}m(a,d);return a}(n)})(require,exports,module);
"object"===typeof window&&(ts=twoside("peasy/logicparser.js"),require=ts.require,exports=ts.exports,module=ts.module);
(function(n,f,p){var h,m,d,a,b,e,c,l,v={}.hasOwnProperty,s=function(b,a){function u(){this.constructor=b}for(var q in a)v.call(a,q)&&(b[q]=a[q]);u.prototype=a.prototype;b.prototype=new u;b.__super__=a.prototype;return b},t=[].slice;n=n("./parser");f=p.exports=function(a){function g(){var a;g.__super__.constructor.apply(this,arguments);a=this;this.parse=function(b,g,c){null==g&&(g=a.root);null==c&&(c=0);a.data=b;a.cur=c;a.trail=new m;a.ruleStack={};a.cache={};return g()};this.bind=function(b,g){b.bind(a.trail.deref(g));
return!0};this.unify=function(b,g,c){null==c&&(c=function(b,a){return b===a});return a.trail.unify(b,g,c)};this.unifyList=function(b,g,c){var d,e,r,f;null==c&&(c=function(b,a){return b===a});e=b.length;if(g.length!==e)return!1;f=a.trail.unify;for(d=r=0;0<=e?r<e:r>e;d=0<=e?++r:--r)if(!f(b[d],g[d],c))return!1;return!0};this.orp=function(){var b,g;g=1<=arguments.length?t.call(arguments,0):[];g=function(){var c,d,e;e=[];c=0;for(d=g.length;c<d;c++)b=g[c],e.push("string"===typeof b?a.literal(b):b);return e}();
return function(){var b,c,q,d,e;d=a.cur;c=g.length;for(b=e=0;0<=c?e<c:e>c;b=0<=c?++e:--e){a.cur=d;a.trail=new m;if(q=g[b]())break;b!==c-1&&a.trail.undo()}return q}};this.unifyChar=function(g){return function(){var c;g=a.trail.deref(g);if(g instanceof b)return c=a.data[a.cur++],g.bind(c),c;if(a.data[a.cur]===g)return a.cur++,g}};this.unifyDigit=function(g){return function(){var c;c=a.data[a.cur];if("0"<=c&&"9">=c){g=a.trail.deref(g);if(g instanceof b)return a.cur++,g.bind(c),c;if(g===c)return a.cur++,
c}}};this.unifyLetter=function(b){return function(){var g;g=a.data[a.cur];if("a"<=b&&"z">=b||"A"<=b&&"Z">=b){b=a.trail.deref(b);if(b instanceof Va)return b.bind(g),a.cur++,g;if(b===g)return a.cur++,g}}};this.unifyLower=function(g){return function(){var c;c=a.data[a.cur];if("a"<=g&&"z">=g){g=a.trail.deref(g);if(g instanceof b)return g.bind(c),a.cur++,c;if(g===c)return a.cur++,c}}};this.unifyUpper=function(g){return function(){var c;c=a.data[a.cur];if("A"<=g&&"Z">=g){g=a.trail.deref(g);if(g instanceof
b)return g.bind(c),a.cur++,c;if(g===c)return a.cur++,c}}};this.unifyIdentifier=function(b){return function(){var g;if(g=a.identifier()&&a.unify(b,g))return g}}}s(g,a);return g}(n);f.Error=p=function(){function b(a,c,d){this.exp=a;this.message=null!=c?c:"";this.stack=null!=d?d:this}b.prototype.toString=function(){return""+this.constructor.name+": "+this.exp+" >>> "+this.message};return b}();f.BindingError=function(b){function a(){return a.__super__.constructor.apply(this,arguments)}s(a,b);return a}(p);
f.Trail=m=function(){function a(b){this.data=null!=b?b:{}}a.prototype.copy=function(){return new a(_.extend({},this.data))};a.prototype.set=function(b,a){var c;c=this.data;if(!c.hasOwnProperty(b.name))return c[b.name]=[b,a]};a.prototype.undo=function(){var b,a,c,d;c=this.data;d=[];for(b in c)a=c[b],d.push(a[0].binding=a[1]);return d};a.prototype.deref=function(b){return(null!=b?"function"===typeof b.deref?b.deref(this):void 0:void 0)||b};a.prototype.getvalue=function(b,a){var c;null==a&&(a={});return(c=
null!=b?b.getvalue:void 0)?c.call(b,this,a):b};a.prototype.unify=function(a,c,d){a=this.deref(a);c=this.deref(c);return a instanceof b?(this.set(a,a.binding),a.binding=c,!0):c instanceof b?(this.set(c,c.binding),c.binding=a,!0):(null!=a?"function"===typeof a.unify?a.unify(c,this):void 0:void 0)||(null!=c?"function"===typeof c.unify?c.unify(a,this):void 0:void 0)||d(a,c)};return a}();f.Var=b=function(){function b(a,c){this.name=null!=a?a:"";this.binding=null!=c?c:this}b.prototype.deref=function(a){var c,
d,e,f,h,k;e=this.binding;if(e!==this&&e instanceof b)for(c=[this],d=1;;){c.push(e);f=e;e=f.binding;d++;if(e===f){d=h=0;for(k=c.length-2;0<=k?h<k:h>k;d=0<=k?++h:--h)f=c[d],f.binding=e,a.set(f,c[d+1]);return e}if(!(e instanceof b)){d=h=0;for(k=c.length-1;0<=k?h<k:h>k;d=0<=k?++h:--h)f=c[d],f.binding=e,a.set(f,c[d+1]);return e}}else return e};b.prototype.bind=function(b,a){a.set(this,this.binding);return this.binding=a.deref(b)};b.prototype.getvalue=function(a,c){var d,e;null==c&&(c={});d=this.name;if(c.hasOwnProperty(d))return c[d];
e=this.deref(a);e instanceof b||(e=a.getvalue(e,c));return c[d]=e};b.prototype.toString=function(){return"vari("+this.name+")"};return b}();l=/\s*,\s*|\s+/;c={};f.vari=function(a){var d;null==a&&(a="");d=c[a]||1;c[a]=d+1;return new b(a+d)};f.vars=function(b){var a,c,d,e;d=split(b,l);e=[];a=0;for(c=d.length;a<c;a++)b=d[a],e.push(vari(b));return e};f.DummyVar=function(b){function a(b){this.name="_$"+b}s(a,b);a.prototype.deref=function(b){return this};a.prototype.getvalue=function(b,a){var c,d;null==
a&&(a={});c=this.name;if(a.hasOwnProperty(c))return a[c];d=this.binding;d!==this&&(d=b.getvalue(d,a));return a[c]=d};return a}(b);f.dummy=e=function(a){var b;b=c[a]||1;c[a]=b+1;return new f.DummyVar(a+b)};f.dummies=function(a){var b,c,d,f;d=split(a,l);f=[];b=0;for(c=d.length;b<c;b++)a=d[b],f.push(new e(a));return f};f.UObject=a=function(){function b(a){this.data=a}b.prototype.getvalue=function(a,c){var d,e,f,h,k,l;f={};d=!1;l=this.data;for(e in l)k=l[e],h=a.getvalue(k,c),h!==k&&(d=!0),f[e]=h;return d?
new b(f):this};b.prototype.unify=function(a,c,d){var e,f,h,k;null==d&&(d=function(a,b){return a===b});f=this.data;h=a instanceof b?a.data:a;k=Object.keys(a);for(e in f){a=k.indexOf(e);if(-1===a||!c.unify(f[e],h[e],d))return!1;k.splice(a,1)}return 0!==k.length?!1:!0};return b}();f.uobject=function(b){return new a(b)};f.UArray=d=function(){function a(b){this.data=b}a.prototype.getvalue=function(b,c){var d,e,f,h,k,l,m;null==c&&(c={});e=[];d=!1;m=this.data;k=0;for(l=m.length;k<l;k++)h=m[k],f=b.getvalue(h,
c),f!==h&&(d=!0),e.push(f);return d?new a(e):this};a.prototype.unify=function(a,b,c){var d,e,f,h;null==c&&(c=function(a,b){return a===b});e=this.data;f=a.data||a;d=this.data.length;if(d!==a.length)return!1;for(a=h=0;0<=d?h<d:h>d;a=0<=d?++h:--h)if(!b.unify(e[a],f[a],c))return!1;return!0};a.prototype.toString=function(){return this.data.toString()};return a}();f.uarray=function(a){return new d(a)};f.Cons=h=function(){function a(b,c){this.head=b;this.tail=c}a.prototype.getvalue=function(b,c){var d,e,
f,h;null==c&&(c={});d=this.head;f=this.tail;e=b.getvalue(d,c);h=b.getvalue(f,c);return e===d&&h===f?this:new a(e,h)};a.prototype.unify=function(b,c,d){null==d&&(d=function(a,b){return a===b});return b instanceof a?c.unify(this.head,b.head,d)?c.unify(this.tail,b.tail,d):!1:!1};a.prototype.flatString=function(){var b,c;b=""+this.head;c=this.tail;return b=null===c?b+"":c instanceof a?b+","+c.flatString():b+c.toString()};a.prototype.toString=function(){return"cons("+this.head+", "+this.tail+")"};return a}();
f.cons=function(a,b){return new h(a,b)};f.conslist=function(){var a,b,c,d;a=1<=arguments.length?t.call(arguments,0):[];c=null;for(b=d=a.length-1;0<=d;b=d+=-1)c=new h([a[b],c]);return c};f.unifiable=function(b){return _.isArray(b)?new d(b):_.isObject(b)?new a(b):b}})(require,exports,module);"object"===typeof window&&(ts=twoside("peasy/index.js"),require=ts.require,exports=ts.exports,module=ts.module);
(function(n,f,p){f=p.exports={Parser:n("./parser"),LogicParser:n("./logicparser"),LineParser:n("./lineparser"),debugging:!1,testing:!1,debug:function(h){if(f.debugging)return console.log(h)},warn:function(h){if(f.debugging||f.testing)return console.log(h)},Charset:function(f){var m,d,a;d=0;for(a=f.length;d<a;d++)m=f[d],this[m]=!0;return this},charset:function(h){return new f.Charset(h)},inCharset:function(h,m){f.warn("peasy.inCharset(char, set) is deprecated, use set.contain(char) instead.");return m.hasOwnProperty(h)},
in_:f.inCharset,isdigit:function(f){return"0"<=f&&"9">=f},isletter:function(f){return"a"<=f&&"z">=f||"A"<=f&&"Z">=f},islower:function(f){return"a"<=f&&"z">=f},isupper:function(f){return"A"<=f&&"Z">=f},isIdentifierLetter:function(f){return"$"===f||"_"===f||"a"<=f&&"z">=f||"A"<=f&&"Z">=f||"0"<=f&&"9">=f},digits:"0123456789",lowers:"abcdefghijklmnopqrstuvwxyz",uppers:"ABCDEFGHIJKLMNOPQRSTUVWXYZ",letters:f.lowers+f.uppers,letterDigits:f.letterDigits};f.Charset.prototype.contain=function(f){return this.hasOwnProperty(f)}})(require,
exports,module);
