// Generated by CoffeeScript 1.6.2
(function() {
  var char, hasOwnProperty, p, parse1, parse2, parse3, parse4, parse5, parser, setupGrammar, xexports, _ref;

  _ref = parser = p = require("../lib/peasy.js"), setupGrammar = _ref.setupGrammar, char = _ref.char;

  hasOwnProperty = Object.hasOwnProperty;

  parse1 = function(text) {
    var grammar, makeGrammar;

    makeGrammar = function(info) {
      var a, b, rules, x;

      a = char(info, 'a');
      b = char(info, 'b');
      x = char(info, 'x');
      rules = {
        A: function(start) {
          var m;

          return (m = rules.A(start)) && x(info.cursor) && m + 'x' || m || a(start);
        },
        __leftRecursives: ['A']
      };
      return setupGrammar(info, rules);
    };
    grammar = makeGrammar({
      data: text,
      cursor: 0
    });
    return grammar.A(0);
  };

  parse2 = function(text) {
    var grammar, makeGrammar;

    makeGrammar = function(info) {
      var a, b, rules, x;

      a = char(info, 'a');
      b = char(info, 'b');
      x = char(info, 'x');
      rules = {
        A: function(start) {
          var m;

          return (m = rules.B(start)) && x(info.cursor) && m + 'x' || m || a(start);
        },
        B: function(start) {
          return rules.A(start) || b(start);
        },
        __leftRecursives: ['A', 'B']
      };
      return setupGrammar(info, rules);
    };
    grammar = makeGrammar({
      data: text,
      cursor: 0
    });
    return grammar.A(0);
  };

  parse3 = function(text) {
    var grammar, makeGrammar;

    makeGrammar = function(info) {
      var a, b, rules, x;

      a = char(info, 'a');
      b = char(info, 'b');
      x = char(info, 'x');
      rules = {
        A: function(start) {
          var m;

          return (m = rules.B(start)) && x(info.cursor) && m + 'x' || m || a(start);
        },
        B: function(start) {
          return rules.C(start);
        },
        C: function(start) {
          return rules.A(start) || b(start);
        },
        __leftRecursives: ['A', 'B', 'C']
      };
      return setupGrammar(info, rules);
    };
    grammar = makeGrammar({
      data: text,
      cursor: 0
    });
    return grammar.A(0);
  };

  parse4 = function(text) {
    var grammar, makeGrammar;

    makeGrammar = function(info) {
      var a, b, rules, x, y;

      a = char(info, 'a');
      b = char(info, 'b');
      x = char(info, 'x');
      y = char(info, 'y');
      rules = {
        A: function(start) {
          var m;

          return (m = rules.B(start)) && x(info.cursor) && m + 'x' || m || a(start);
        },
        B: function(start) {
          var m;

          return (m = rules.A(start)) && y(info.cursor) && m + 'y' || rules.C(start);
        },
        C: function(start) {
          return rules.A(start) || b(start);
        },
        __leftRecursives: ['A', 'B', 'C']
      };
      return setupGrammar(info, rules);
    };
    grammar = makeGrammar({
      data: text,
      cursor: 0
    });
    return grammar.A(0);
  };

  parse5 = function(text) {
    var grammar, makeGrammar;

    makeGrammar = function(info) {
      var a, b, rules, x, y, z;

      a = char(info, 'a');
      b = char(info, 'b');
      x = char(info, 'x');
      y = char(info, 'y');
      z = char(info, 'z');
      rules = {
        Root: function(start) {
          var m;

          return (m = rules.A(start)) && z(info.cursor) && m + 'z';
        },
        A: function(start) {
          var m;

          return (m = rules.B(start)) && x(info.cursor) && m + 'x' || m || a(start);
        },
        B: function(start) {
          var m;

          return (m = rules.A(start)) && y(info.cursor) && m + 'y' || rules.C(start);
        },
        C: function(start) {
          return rules.A(start) || b(start);
        },
        __leftRecursives: ['A', 'B', 'C']
      };
      return setupGrammar(info, rules);
    };
    grammar = makeGrammar({
      data: text,
      cursor: 0
    });
    return grammar.Root(0);
  };

  xexports = {};

  exports.Test = {
    "test A: Ax|a": function(test) {
      var parse;

      parse = parse1;
      test.equal(parse('a'), 'a');
      test.equal(parse('ax'), 'ax');
      test.equal(parse('axx'), 'axx');
      test.equal(parse('axxx'), 'axxx');
      return test.done();
    },
    "test A: Bx|a; B:A|b": function(test) {
      var parse;

      parse = parse2;
      test.equal(parse('a'), 'a');
      test.equal(parse('ax'), 'ax');
      test.equal(parse('axx'), 'axx');
      test.equal(parse('axxx'), 'axxx');
      test.equal(parse('b'), 'b');
      test.equal(parse('bx'), 'bx');
      test.equal(parse('bxxx'), 'bxxx');
      test.equal(parse('bxg'), 'bx');
      test.equal(parse('bxxg'), 'bxx');
      test.equal(parse('bxxxg'), 'bxxx');
      test.equal(parse('fg'), void 0);
      test.equal(parse(''), void 0);
      return test.done();
    },
    "test A: Bx|a; B:C; C:A|b": function(test) {
      var parse;

      parse = parse3;
      test.equal(parse('a'), 'a');
      test.equal(parse('ax'), 'ax');
      test.equal(parse('axx'), 'axx');
      test.equal(parse('axxx'), 'axxx');
      test.equal(parse('b'), 'b');
      test.equal(parse('bx'), 'bx');
      test.equal(parse('bxxx'), 'bxxx');
      test.equal(parse('bxg'), 'bx');
      test.equal(parse('bxxg'), 'bxx');
      test.equal(parse('bxxxg'), 'bxxx');
      test.equal(parse('fg'), void 0);
      test.equal(parse(''), void 0);
      return test.done();
    },
    "test A: Bx|a; B:C|Ay; C:A|b": function(test) {
      var parse;

      parse = parse4;
      test.equal(parse('a'), 'a');
      test.equal(parse('ax'), 'ax');
      test.equal(parse('axx'), 'axx');
      test.equal(parse('axxx'), 'axxx');
      test.equal(parse('ay'), 'ay');
      test.equal(parse('ayx'), 'ayx');
      test.equal(parse('ayxyx'), 'ayxyx');
      test.equal(parse('bxx'), 'bxx');
      test.equal(parse('ayxxx'), 'ayxxx');
      test.equal(parse('ayxmxx'), 'ayx');
      test.equal(parse('b'), 'b');
      test.equal(parse('bx'), 'bx');
      test.equal(parse('bxxx'), 'bxxx');
      test.equal(parse('bxg'), 'bx');
      test.equal(parse('bxxg'), 'bxx');
      test.equal(parse('bxxxg'), 'bxxx');
      test.equal(parse('fg'), void 0);
      test.equal(parse(''), void 0);
      return test.done();
    },
    "test Start: Az; A: Bx|a; B:C|Ay; C:A|b": function(test) {
      var parse;

      parse = parse5;
      test.equal(parse('az'), 'az');
      test.equal(parse('axz'), 'axz');
      test.equal(parse('axxz'), 'axxz');
      test.equal(parse('axxxz'), 'axxxz');
      test.equal(parse('ayz'), 'ayz');
      test.equal(parse('ayxz'), 'ayxz');
      test.equal(parse('ayxyxz'), 'ayxyxz');
      test.equal(parse('bxxz'), 'bxxz');
      test.equal(parse('ayxxxz'), 'ayxxxz');
      test.equal(parse('ayxmxxz'), void 0);
      test.equal(parse('bz'), 'bz');
      test.equal(parse('bxz'), 'bxz');
      test.equal(parse('bxxxz'), 'bxxxz');
      test.equal(parse('bxgz'), void 0);
      test.equal(parse('bxxgz'), void 0);
      test.equal(parse('bxxxgz'), void 0);
      test.equal(parse('fg'), void 0);
      test.equal(parse(''), void 0);
      return test.done();
    }
  };

}).call(this);

/*
//@ sourceMappingURL=testpeasy.map
*/
